PUT http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpMSIsImlkIjoiNjQ0NTEyYzFjZjkyNWQ5MWJiZDJhMWVlIiwiaWF0IjoxNjgyMjU3MDk2LCJleHAiOjE2ODIyNjA2OTZ9.9oaGFwNfwIXKYLUDN_qizLMu0k-wLmo5TZURBXuhais

{
    
}

//ota oikea Bearer <koodi> try_login-requestista!